// This file will be generated by Supabase CLI
// Run: supabase gen types typescript --project-id YOUR_PROJECT_ID > supabase/types/database.types.ts

export interface Database {
  public: {
    Tables: {
      // Add your table types here
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          role: string
          location_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          role: string
          location_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          role?: string
          location_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // Add more tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
